steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-f','backend/Dockerfile','-t','europe-central2-docker.pkg.dev/idswyft-production/idswyft/api:latest','.']
images: ['europe-central2-docker.pkg.dev/idswyft-production/idswyft/api:latest']
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
